// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhCOmSM7EfJHeq-CN_6H_SQunTY_VbTM',
    appId: '1:828125426845:web:d69fdc47f28c4bb4ac5074',
    messagingSenderId: '828125426845',
    projectId: 'scheduarappbackend',
    authDomain: 'scheduarappbackend.firebaseapp.com',
    databaseURL: 'https://scheduarappbackend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scheduarappbackend.appspot.com',
    measurementId: 'G-66XMTJ2ZRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldUAfVO1dud1jBs2h8fKbKxNfEzt5vIY',
    appId: '1:828125426845:android:747831e40e94a43fac5074',
    messagingSenderId: '828125426845',
    projectId: 'scheduarappbackend',
    databaseURL: 'https://scheduarappbackend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scheduarappbackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUd4eqKMT4rt1-tANmYvsico1O2Pvo4YM',
    appId: '1:828125426845:ios:8f45570aa86d4f85ac5074',
    messagingSenderId: '828125426845',
    projectId: 'scheduarappbackend',
    databaseURL: 'https://scheduarappbackend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scheduarappbackend.appspot.com',
    androidClientId: '828125426845-8b7djg5jgrpksp50hlq6fc34vna0o40t.apps.googleusercontent.com',
    iosClientId: '828125426845-j3vjiq21582ob8s7sr3qpm855l3ej027.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUd4eqKMT4rt1-tANmYvsico1O2Pvo4YM',
    appId: '1:828125426845:ios:02aa9257ef6b463cac5074',
    messagingSenderId: '828125426845',
    projectId: 'scheduarappbackend',
    databaseURL: 'https://scheduarappbackend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scheduarappbackend.appspot.com',
    androidClientId: '828125426845-8b7djg5jgrpksp50hlq6fc34vna0o40t.apps.googleusercontent.com',
    iosClientId: '828125426845-rnd6eeo5nu1b63u3t21j0d46er9qu15g.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduler.RunnerTests',
  );
}
