// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClQ1JtwxsF-0xhTAhhARvxjtWWDHug9vw',
    appId: '1:229538634287:web:f5acafccd80c6c6cf744da',
    messagingSenderId: '229538634287',
    projectId: 'the-scheduler-app',
    authDomain: 'the-scheduler-app.firebaseapp.com',
    storageBucket: 'the-scheduler-app.appspot.com',
    measurementId: 'G-EHX38128W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEin8in3hkTNS6lP2c2LUyOjOZSYyTk3E',
    appId: '1:229538634287:android:212d5f126c6b454ff744da',
    messagingSenderId: '229538634287',
    projectId: 'the-scheduler-app',
    storageBucket: 'the-scheduler-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfBZkxMtg89SYobEu6FWwVIpdK016DQTg',
    appId: '1:229538634287:ios:d8aca44eb3bdc723f744da',
    messagingSenderId: '229538634287',
    projectId: 'the-scheduler-app',
    storageBucket: 'the-scheduler-app.appspot.com',
    androidClientId:
        '229538634287-uobetv4padturdqu2k7ol2cn9kpb7ead.apps.googleusercontent.com',
    iosClientId:
        '229538634287-te9rqdjonvemnjk4hmdbg7o9e1h3obdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfBZkxMtg89SYobEu6FWwVIpdK016DQTg',
    appId: '1:229538634287:ios:cd717f9971f40179f744da',
    messagingSenderId: '229538634287',
    projectId: 'the-scheduler-app',
    storageBucket: 'the-scheduler-app.appspot.com',
    androidClientId:
        '229538634287-uobetv4padturdqu2k7ol2cn9kpb7ead.apps.googleusercontent.com',
    iosClientId:
        '229538634287-0ehea4io12akts7i6pup1p74tofo7e57.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduler.RunnerTests',
  );
}
